# -*- coding: utf-8 -*-
"""Day2_AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uI4jdqPROK8n97qNoRyPqqLnyI-metBO

### Library Installation
"""



import streamlit as st
import pandas as pd
import pickle

"""### Initialize Website"""

st.set_page_config(page_title="Smart Hospital", page_icon="💊", layout="centered")

@st.cache_resource
def load_mymodel():
  with open('hospital_modell.pkl', 'rb') as f:
    bundle = pickle.load(f)
  return bundle

bundle = load_mymodel()
knn = bundle['model']
scaler = bundle['scaler']
le_department = bundle['le_department']

st.title("💊 Smart Hospital by Dr. Sidney")
st.write("Enter the patient's symptom data below to get a recommendation for a specialist department")
st.markdown("----")

col1, col2 = st.columns(2)

with col1:
    st.subheader("📊 Physical Data & Vital Signs")
    age = st.number_input("Patient Age (Years)", min_value=0, max_value=120, value=25)
    gender_input = st.selectbox("Patient Gender", ["Male", "Female", "Unknown"])

    temperature_level = st.selectbox(
        "Body Temperature Level",
        ["Below 37°C", "37-38°C", "Above 38°C", "Unknown"]
    )

    heart_rate_level = st.selectbox(
        "Heart Rate Level (BPM)",
        ["Below 60 bpm", "60-100 bpm", "Above 100 bpm", "Unknown"]
    )

    duration = st.selectbox(
        "Duration of Symptoms",
        ["Less than 1 day", "1-3 days", "4-7 days", "More than 1 week", "Unknown"]
    )

with col2:
  st.subheader("🤧 Symptoms")
  fever = 1 if st.checkbox("Fever") else 0
  cough = 1 if st.checkbox("Cough") else 0
  headache = 1 if st.checkbox("Headache") else 0
  chest_pain = 1 if st.checkbox("Chest Pain") else 0
  stomach_pain = 1 if st.checkbox("Stomach Pain") else 0
  shortness_breath = 1 if st.checkbox("Shortness of Breath") else 0
  nausea_vomit = 1 if st.checkbox("Nausea / Vomiting") else 0
  dizziness = 1 if st.checkbox("Dizziness") else 0
  skin_rash = 1 if st.checkbox("Skin Rash") else 0

  st.subheader("📜 Medical History")
  diabetes = 1 if st.checkbox("Diabetes") else 0
  asthma = 1 if st.checkbox("Asthma") else 0
  hypertension = 1 if st.checkbox("Hypertension") else 0
  heart_disease = 1 if st.checkbox("Heart Disease") else 0

"""### Data Processing"""

if st.button("🚀 Process Patient Triage", type="primary", use_container_width=True):
  gender_encoded = {'Male':0, 'Female':1, 'Unknown':2}[gender_input]
  temp_encoded = {'Below 37°C':0, '37-38°C':1, 'Above 38°C':2, 'Unknown':3}[temperature_level]
  hr_encoded = {'Below 60 bpm':0, '60-100 bpm':1, 'Above 100 bpm':2, 'Unknown':3}[heart_rate_level]
  duration_encoded = {"Less than 1 day":0, "1-3 days":1, "4-7 days":2, "More than 1 week":3, "Unknown":4}[duration]

  new_patient = pd.DataFrame([{
      'age' : age, 'gender' : gender_encoded, 'fever':fever, 'cough':cough, 'headache':headache,
      'chest_pain':chest_pain, 'stomach_pain':stomach_pain, 'shortness_breath':shortness_breath,
      'nausea_vomit':nausea_vomit, 'dizziness':dizziness, 'skin_rash':skin_rash, 'temperature_level':temp_encoded,
      'heart_rate_level':hr_encoded, 'duration':duration_encoded, 'diabetes':diabetes, 'asthma':asthma,
      'hypertension':hypertension, 'heart_disease':heart_disease
  }])

  cols_to_scale = bundle['cols_to_scale']
  new_patient[cols_to_scale] = scaler.transform(new_patient[cols_to_scale])

  pred_code = knn.predict(new_patient)[0]
  proba = knn.predict_proba(new_patient)[0]

  dept_name = le_department.inverse_transform([pred_code])[0]
  confidence = proba[pred_code] * 100

  st.success(f'### 🎯 Recommended Department : **{dept_name}**')
  st.info(f"⭐ AI Confidence Level:** {confidence:.1f}%")

  with st.expander("🔍 View Probability Details for All Departments"):
    for i, name in enumerate(le_department.classes_):
      score = proba[i] * 100
      st.write(f"**{name}**)")
      st.progress(int(score))
      st.write(f"{score:.1f}%")
